# Generated by Django 2.0.1 on 2019-05-30 08:35

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0019_delete_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('title_classes', models.CharField(default='Занятия в школе', max_length=50, verbose_name="Заголовок 'Занятия в школе'")),
                ('description_classes', wagtail.core.fields.RichTextField(default='Text', verbose_name='Описание под заголовоком')),
                ('time_classes_title', models.CharField(default='Расписание занятий', max_length=50, verbose_name="Заголовок 'Расписание занятий'")),
                ('time_classes_description', wagtail.core.fields.RichTextField(default='Text', verbose_name="Описание под 'расписание занятий'")),
                ('title_reviews', models.CharField(default='Что говорят о нас', max_length=50, verbose_name='Заголвок селекции отзывы')),
                ('description', wagtail.core.fields.RichTextField(default='Text', verbose_name='Текст под селекции отзывы')),
                ('image_classes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name="Картинка для 'Занятия в школе'")),
            ],
            options={
                'verbose_name': 'Добавить страницу Занятия (не трогать)',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OneGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(default='Первая группа', max_length=50, verbose_name='Заголовок')),
                ('description', wagtail.core.fields.RichTextField(default='Text', verbose_name='Описание')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Картинка группы (иконка)')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='onegroup_users', to='classes.ClassesPage')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(default='Имя человка', max_length=50, verbose_name='Имя человка')),
                ('description', wagtail.core.fields.RichTextField(default='Text', verbose_name='Отзыв')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Картинка человека')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='classes.ClassesPage')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
    ]
