# Generated by Django 2.0.1 on 2019-07-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onegallerypage',
            name='href',
            field=models.CharField(default='href', max_length=225, verbose_name='Ссылка на изображение в unplash'),
        ),
    ]
