# Generated by Django 2.0.1 on 2019-07-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_onegallerypage_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onegallerypage',
            name='href',
            field=models.CharField(default='https://source.unsplash.com/', max_length=225, verbose_name='Ссылка на изображение в unplash'),
        ),
    ]
