# Generated by Django 2.2.1 on 2019-05-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='text',
        ),
        migrations.AddField(
            model_name='header',
            name='email',
            field=models.EmailField(default='text', max_length=254, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='header',
            name='phone',
            field=models.CharField(default='text', max_length=50, verbose_name='Номер телефона'),
        ),
    ]
