# Generated by Django 2.0.1 on 2019-06-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_orlan_docs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutdocsorlan',
            name='second_image',
        ),
    ]
