# Generated by Django 2.0.1 on 2019-06-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_orlan_docs', '0002_remove_aboutdocsorlan_second_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star_info',
            name='page',
        ),
        migrations.AlterModelOptions(
            name='aboutdocsorlan',
            options={},
        ),
        migrations.RemoveField(
            model_name='aboutdocsorlan',
            name='first_image',
        ),
        migrations.DeleteModel(
            name='Star_info',
        ),
    ]
