# Generated by Django 2.0.1 on 2019-06-14 21:47

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about_orlan_docs', '0003_auto_20190614_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutdocsorlan',
            options={'verbose_name': 'Об автошколе'},
        ),
        migrations.AddField(
            model_name='aboutdocsorlan',
            name='brief_information',
            field=wagtail.core.fields.RichTextField(default='Default', verbose_name='Информация об учреждении'),
        ),
        migrations.AddField(
            model_name='aboutdocsorlan',
            name='date_of_creation',
            field=wagtail.core.fields.RichTextField(default='Default', verbose_name='Дата создания тектс'),
        ),
        migrations.AddField(
            model_name='aboutdocsorlan',
            name='driving_schedule',
            field=wagtail.core.fields.RichTextField(default='Default', verbose_name='График вождения'),
        ),
        migrations.AddField(
            model_name='aboutdocsorlan',
            name='email',
            field=wagtail.core.fields.RichTextField(default='Default', verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='aboutdocsorlan',
            name='founder',
            field=wagtail.core.fields.RichTextField(default='Default', verbose_name='Учредитель'),
        ),
        migrations.AddField(
            model_name='aboutdocsorlan',
            name='locate',
            field=wagtail.core.fields.RichTextField(default='Default', verbose_name='Местонахождение'),
        ),
        migrations.AddField(
            model_name='aboutdocsorlan',
            name='numbers',
            field=wagtail.core.fields.RichTextField(default='Default', verbose_name='Контактные телефоны'),
        ),
        migrations.AddField(
            model_name='aboutdocsorlan',
            name='schedule',
            field=wagtail.core.fields.RichTextField(default='Default', verbose_name='График работы'),
        ),
    ]
