# Generated by Django 2.0.1 on 2019-06-15 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('about_orlan_docs', '0004_auto_20190615_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildAboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Создать дочернюю страницу об автошколе',
            },
            bases=('wagtailcore.page',),
        ),
    ]
