# Generated by Django 2.0.1 on 2019-06-15 20:17

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about_orlan_docs', '0005_childaboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='childaboutpage',
            name='body',
            field=wagtail.core.fields.StreamField([('h1', wagtail.core.blocks.CharBlock(classname='h1 заголовок')), ('h2', wagtail.core.blocks.CharBlock(classname='h2 заголовок')), ('h3', wagtail.core.blocks.CharBlock(classname='h3 заголовок')), ('h4', wagtail.core.blocks.CharBlock(classname='h4 заголовок')), ('h5', wagtail.core.blocks.CharBlock(classname='h5 заголовок')), ('Текст', wagtail.core.blocks.RichTextBlock()), ('ДокументPDF', wagtail.documents.blocks.DocumentChooserBlock(classname='документ pdf')), ('Фотография', wagtail.images.blocks.ImageChooserBlock(classname='фотография')), ('модульныйблок', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('Иконка', wagtail.images.blocks.ImageChooserBlock(classname='иконка')), ('Заголовок', wagtail.core.blocks.CharBlock(classname='заголовок для блока')), ('Описание', wagtail.core.blocks.RichTextBlock())])))], default=None),
        ),
    ]
