# Generated by Django 2.0.1 on 2019-06-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_orlan_docs', '0008_auto_20190616_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childaboutpage',
            old_name='bl',
            new_name='bl_ones',
        ),
    ]
