# Generated by Django 2.0.1 on 2019-06-16 16:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about_orlan_docs', '0010_auto_20190616_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childaboutpage',
            name='bl_ones',
            field=wagtail.core.fields.StreamField([('ДокументPDF', wagtail.documents.blocks.DocumentChooserBlock(classname='документ pdf')), ('мб_с_описанием', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(classname='иконка')), ('title', wagtail.core.blocks.CharBlock(classname='заголовок для блока')), ('description', wagtail.core.blocks.RichTextBlock())]))), ('мб', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(classname='иконка')), ('title', wagtail.core.blocks.CharBlock(classname='заголовок для блока'))])))], default=None, verbose_name='Одинарный блок'),
        ),
        migrations.AlterField(
            model_name='childaboutpage',
            name='body',
            field=wagtail.core.fields.StreamField([('h1', wagtail.core.blocks.CharBlock(classname='h1 заголовок')), ('h2', wagtail.core.blocks.CharBlock(classname='h2 заголовок')), ('h3', wagtail.core.blocks.CharBlock(classname='h3 заголовок')), ('h4', wagtail.core.blocks.CharBlock(classname='h4 заголовок')), ('h5', wagtail.core.blocks.CharBlock(classname='h5 заголовок')), ('Текст', wagtail.core.blocks.RichTextBlock())], default=None, verbose_name='Обычный текст'),
        ),
    ]
