# Generated by Django 2.0.1 on 2019-06-16 18:37

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about_orlan_docs', '0011_auto_20190616_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='childaboutpage',
            name='bl_many',
            field=wagtail.core.fields.StreamField([('ДокументPDF', wagtail.documents.blocks.DocumentChooserBlock(classname='документ pdf')), ('мб_с_описанием', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(classname='иконка')), ('title', wagtail.core.blocks.CharBlock(classname='заголовок для блока')), ('description', wagtail.core.blocks.RichTextBlock())]))), ('мб', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(classname='иконка')), ('title', wagtail.core.blocks.CharBlock(classname='заголовок для блока'))])))], default=None, verbose_name='Длинный блок'),
        ),
    ]
