# Generated by Django 2.0.1 on 2019-07-10 21:53

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about_orlan_docs', '0014_auto_20190705_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childaboutpage',
            name='bl_many',
        ),
        migrations.RemoveField(
            model_name='childaboutpage',
            name='bl_ones',
        ),
        migrations.AlterField(
            model_name='childaboutpage',
            name='body',
            field=wagtail.core.fields.StreamField([('Текст', wagtail.core.blocks.RichTextBlock()), ('документ', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(classname='Заголовок')), ('static_name', wagtail.core.blocks.CharBlock(classname='ссылка на документ'))]))), ('мб_с_описанием', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(classname='иконка')), ('title', wagtail.core.blocks.CharBlock(classname='заголовок для блока')), ('description', wagtail.core.blocks.RichTextBlock())]))), ('мб', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(classname='иконка')), ('title', wagtail.core.blocks.CharBlock(classname='заголовок для блока'))]))), ('документ_строка', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(classname='Заголовок')), ('static_name', wagtail.core.blocks.CharBlock(classname='ссылка на документ'))]))), ('мб_с_описанием_строка', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(classname='иконка')), ('title', wagtail.core.blocks.CharBlock(classname='заголовок для блока')), ('description', wagtail.core.blocks.RichTextBlock())]))), ('мб_строка', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(classname='иконка')), ('title', wagtail.core.blocks.CharBlock(classname='заголовок для блока'))])))], blank=True, default=None, null=True, verbose_name='Обычный текст'),
        ),
    ]
