# Generated by Django 2.0.1 on 2019-05-30 08:35

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('geo_description', wagtail.core.fields.RichTextField(default='Text', verbose_name='Адрес огранизации')),
                ('phone', wagtail.core.fields.RichTextField(default='Text', verbose_name='Номер телефона')),
                ('email', wagtail.core.fields.RichTextField(default='Text', verbose_name='Введите почту')),
            ],
            options={
                'verbose_name': 'Добавить страницу контактов (не трогать)',
            },
            bases=('wagtailcore.page',),
        ),
    ]
