# Generated by Django 2.0.1 on 2019-05-30 08:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('preview_text', models.CharField(default='text', help_text='Сокращенное содержание статьи\nТекст который отображается на главной странице', max_length=50, verbose_name='Превью текст')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата поста')),
                ('body', wagtail.core.fields.RichTextField(default='text', help_text='Пишите текст статьи', verbose_name='Текст статьи')),
            ],
            options={
                'verbose_name': 'Добавить новую статью (Добавлять как дочернюю страницу к страницы с новостями)',
            },
            bases=('wagtailcore.page',),
        ),
    ]
