# Generated by Django 2.0.1 on 2019-06-11 18:15

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='preview_text',
            field=wagtail.core.fields.RichTextField(default='text', help_text='Сокращенное содержание статьи\nТекст который отображается на главной странице', verbose_name='Превью текст'),
        ),
    ]
