# Generated by Django 2.0.1 on 2019-05-30 08:35

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0019_delete_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningInformationOneObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(default='Заголовок', max_length=50, verbose_name='Заголовок')),
                ('description', wagtail.core.fields.RichTextField(default='Описание', verbose_name='Описание')),
                ('img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Картинка блока информации')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='OneService',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description_title', models.CharField(default='Подготовка водителей категории «В»', max_length=50, verbose_name='Заголовок описания услуги')),
                ('description_text', wagtail.core.fields.RichTextField(default='Описание', verbose_name='Описание услуги')),
                ('title_learning_information', models.CharField(default='Сведения об обучении', max_length=50, verbose_name='Заголовок сведение обучения')),
                ('description_learning_information', wagtail.core.fields.RichTextField(default='Описание', verbose_name='Описание под заголовком')),
                ('img_description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Картинка для категории')),
            ],
            options={
                'verbose_name': 'Добавить услугу',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('selection_title', models.CharField(default='Перечень услуг', max_length=50, verbose_name='Текст перечень услуг')),
                ('selection_description', wagtail.core.fields.RichTextField(default='Описание', verbose_name='Описание перечня услуг')),
            ],
            options={
                'verbose_name': 'страницу со всеми услугами (не трогать!)',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='learninginformationoneobject',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnobj', to='service.OneService'),
        ),
    ]
