# Generated by Django 2.0.1 on 2019-06-19 11:34

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learninginformationoneobject',
            name='img',
        ),
        migrations.RemoveField(
            model_name='learninginformationoneobject',
            name='page',
        ),
        migrations.AddField(
            model_name='oneservice',
            name='description_age',
            field=wagtail.core.fields.RichTextField(default='Описание', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='oneservice',
            name='description_date',
            field=wagtail.core.fields.RichTextField(default='Описание', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='oneservice',
            name='description_price',
            field=wagtail.core.fields.RichTextField(default='Описание', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='oneservice',
            name='title_age',
            field=models.CharField(default='НЕОБХОДИМЫЙ ВОЗРАСТ', max_length=50, verbose_name='НЕОБХОДИМЫЙ ВОЗРАСТ'),
        ),
        migrations.AddField(
            model_name='oneservice',
            name='title_date',
            field=models.CharField(default='СРОК ОБУЧЕНИЯ', max_length=50, verbose_name='СРОК ОБУЧЕНИЯ'),
        ),
        migrations.AddField(
            model_name='oneservice',
            name='title_price',
            field=models.CharField(default='СТОИМОСТЬ ОБУЧЕНИЯ', max_length=50, verbose_name='СТОИМОСТЬ ОБУЧЕНИЯ'),
        ),
        migrations.DeleteModel(
            name='LearningInformationOneObject',
        ),
    ]
