# Generated by Django 2.0.1 on 2019-06-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20190619_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oneservice',
            name='description_text',
        ),
    ]
