# Generated by Django 2.0.1 on 2019-06-19 11:37

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_oneservice_description_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oneservice',
            name='description_learning_information',
        ),
        migrations.AddField(
            model_name='oneservice',
            name='description_text',
            field=wagtail.core.fields.RichTextField(default='Описание', verbose_name='Описание услуги'),
        ),
    ]
