# Generated by Django 2.0.1 on 2019-08-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20190829_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='token',
            field=models.CharField(default='Token', max_length=40),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='age',
            field=models.IntegerField(default=1, verbose_name='Сколько вам лет'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Он валидный'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(default='Name', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.TextField(default='Review', verbose_name='Отзыв'),
        ),
    ]
