# Generated by Django 2.0.1 on 2019-06-11 18:15

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='gallery_description',
        ),
        migrations.AlterField(
            model_name='featured',
            name='description',
            field=wagtail.core.fields.RichTextField(default='Описание', verbose_name='Описание преимущества'),
        ),
        migrations.AlterField(
            model_name='featured',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Изображение должно быть в размером 77 на 77', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Картинка преимущества'),
        ),
        migrations.AlterField(
            model_name='featured',
            name='title',
            field=models.CharField(default='Заголовок', max_length=200, verbose_name='Заголовок преимущества'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='feature_mini_description',
            field=wagtail.core.fields.RichTextField(default='Описание', help_text='Введите небольшое описание для преймуществ', verbose_name='Описание преимуществ'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='feature_title_text',
            field=models.CharField(default='Заголовок', help_text='Введите заголовлок по умолчанию наши преимущества', max_length=200, verbose_name='Заголовок для преимуществ'),
        ),
    ]
