# Generated by Django 2.0.1 on 2019-06-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_homepage_what_they_say_about_us_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured',
            name='image',
        ),
        migrations.RemoveField(
            model_name='featured',
            name='page',
        ),
        migrations.DeleteModel(
            name='Featured',
        ),
    ]
